### ISSUE TITLE
[Bug]: Wrong space in Homepage Stats Card

### ISSUE THREAD

**Issue by Lizetteffkb** [LangaraBeetles/beetles-mobile#114]
### Current Behaviour

The right part (xp and streak) has the wrong position as seen below in screenshot
![Frame 1171275686 (2)](https://github.com/user-attachments/assets/f29a6645-e2bd-42fd-858c-d92905c1c0d7)

### Expected Behaviour

It should be having 33px on the left and 31px on the right for space, or at least visuaslly centred
<img width="375" alt="Home Screen - Guest (12)" src="https://github.com/user-attachments/assets/ef019a08-f0d7-4af8-9f44-edc244903e42">

### Reproduction steps

```bash
Open the app, check the homescreen
```

### Screenshots / Screen Recordings

Paste, drag and drop, or click option below to add your files here.

### Device

iPhone 13 Pro Max

### Operating System

iOS 17.5.1

**Comment by whamester** [comment]
Review with design.
